# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Scientist Association at Mac
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
"Science Faculty is the most diverse faculty at McMaster University; 8 departments covering everything from music cognition to theoretical physics. A group of us saw this diversity and lack of communication platforms between programs. We also saw great opportunities in bringing scientists from diverse fields together to make a difference in graduate student life at McMaster.
Do you want to know what’s happening in other science departments at the opposite side of the campus?"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: none

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/McSAM2015
  - title: facebook
    url: https://www.facebook.com/ScientistAssociation
